/**
 * Omnecor HQ (Android) packaging smoke tests.
 *
 * The Omnecor Android app is **Omnecor HQ** — the React Native / Expo project at
 * packaging/android/omnecor-hq. Its source of truth is `app.config.ts`; the
 * native `android/` Gradle project is generated by `expo prebuild` and is
 * git-ignored, so the generated-file checks are skipped until the project has
 * been prebuilt. Each test corresponds to an audit finding; the failure message
 * says what to fix.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import path from 'path';

const HQ = path.resolve(import.meta.dirname, 'omnecor-hq');
const APP_CONFIG = path.join(HQ, 'app.config.ts');
const PKG_JSON = path.join(HQ, 'package.json');
const ANDROID_APP = path.join(HQ, 'android', 'app');
const ANDROID_MANIFEST = path.join(ANDROID_APP, 'src', 'main', 'AndroidManifest.xml');
const BUILD_GRADLE = path.join(ANDROID_APP, 'build.gradle');

const PACKAGE_ID = 'com.omnecor.mobilehq';

// ── Expo config (app.config.ts — tracked source of truth) ───────────────────

describe('Omnecor HQ Expo config (app.config.ts)', () => {
  const cfg = () => readFileSync(APP_CONFIG, 'utf8');

  it('file exists', () => {
    expect(existsSync(APP_CONFIG), `Missing: ${APP_CONFIG}`).toBe(true);
  });

  it('android package is com.omnecor.mobilehq', () => {
    expect(
      cfg(),
      'Android package must be com.omnecor.mobilehq (drives applicationId + namespace)',
    ).toContain(`"${PACKAGE_ID}"`);
  });

  it('app name is "Omnecor HQ"', () => {
    expect(cfg()).toContain('appName: "Omnecor HQ"');
  });

  it('declares the permissions the app needs', () => {
    const c = cfg();
    for (const perm of [
      'INTERNET',
      'RECORD_AUDIO',
      'POST_NOTIFICATIONS',
      'FOREGROUND_SERVICE_MICROPHONE',
      'WAKE_LOCK',
    ]) {
      expect(
        c,
        `permission ${perm} missing from app.config.ts android.permissions`,
      ).toContain(`"${perm}"`);
    }
  });

  it('runs on the New Architecture (mandatory on Expo SDK 55+)', () => {
    // Expo SDK 55 / RN 0.83 make the New Architecture always-on and removed the
    // `newArchEnabled` opt-in flag from ExpoConfig — so assert the SDK floor and
    // that the config doesn't try to disable it (which SDK 55 would ignore anyway).
    const expoRange: string = JSON.parse(readFileSync(PKG_JSON, 'utf8')).dependencies?.expo ?? '';
    const major = parseInt(expoRange.replace(/[^0-9.]/g, '').split('.')[0] ?? '0', 10);
    expect(major, `expo ${expoRange} must be >= 55 (New Architecture is mandatory)`).toBeGreaterThanOrEqual(55);
    expect(cfg()).not.toContain('newArchEnabled: false');
  });
});

// ── package.json (build scripts + native deps) ──────────────────────────────

describe('Omnecor HQ package.json', () => {
  const pkg = () => JSON.parse(readFileSync(PKG_JSON, 'utf8'));

  it('exposes the apk:debug / apk:release / apk:install build scripts', () => {
    const s = pkg().scripts ?? {};
    for (const script of ['apk:debug', 'apk:release', 'apk:install', 'prebuild:android']) {
      expect(s[script], `package.json scripts.${script} is missing`).toBeTruthy();
    }
  });

  it('depends on llama.rn for on-device GGUF inference', () => {
    expect(
      pkg().dependencies?.['llama.rn'],
      'llama.rn dependency missing — on-device inference is a core Omnecor HQ feature',
    ).toBeTruthy();
  });
});

// ── Generated native project (only present after `expo prebuild`) ───────────

const prebuilt = existsSync(BUILD_GRADLE);

describe.skipIf(!prebuilt)('Generated Android project (after prebuild)', () => {
  it('app/build.gradle applicationId + namespace are com.omnecor.mobilehq', () => {
    const g = readFileSync(BUILD_GRADLE, 'utf8');
    expect(
      g,
      `applicationId in build.gradle must match app.config.ts package: ${PACKAGE_ID}`,
    ).toContain(`applicationId '${PACKAGE_ID}'`);
    expect(g).toContain(`namespace '${PACKAGE_ID}'`);
  });

  it('AndroidManifest declares INTERNET, RECORD_AUDIO and the mic foreground service', () => {
    const m = readFileSync(ANDROID_MANIFEST, 'utf8');
    expect(m, 'INTERNET permission missing — the app cannot reach the desktop backend').toContain(
      'android.permission.INTERNET',
    );
    expect(m, 'RECORD_AUDIO missing — voice input (Whisper STT) needs it').toContain(
      'android.permission.RECORD_AUDIO',
    );
    expect(
      m,
      'FOREGROUND_SERVICE_MICROPHONE missing — always-listening voice mode needs a typed mic FGS',
    ).toContain('android.permission.FOREGROUND_SERVICE_MICROPHONE');
  });

  it('MainActivity is exported=true and has a LAUNCHER intent filter', () => {
    const m = readFileSync(ANDROID_MANIFEST, 'utf8');
    expect(m, 'MainActivity must be exported=true to launch on Android 12+').toContain(
      'android:exported="true"',
    );
    expect(m).toContain('android.intent.category.LAUNCHER');
  });
});
