/**
 * Blueprint Studio — built-in materials database.
 *
 * A curated, fully-offline catalog with *real* mechanical properties so the
 * deterministic calc engine (calcEngine.ts) and the FEA bridge can consume
 * them directly — this is what keeps Sovereign mode fully functional with no
 * web access. Costs are indicative planning estimates (typical US retail,
 * 2025–2026) — live prices come from the cloud-gated web search when allowed.
 *
 * Sources for the numbers:
 *  - Softwood lumber: NDS-style *allowable* design values for No.2 grade
 *    (strengthBasis "allowable" — factors already embedded).
 *  - Metals: ASTM minimum yield/ultimate (basis "yield" — apply an explicit SF).
 *  - Plastics/filaments: manufacturer datasheet typicals (basis "ultimate",
 *    with an FDM layer-adhesion knockdown for Z-loaded prints).
 *  - Fabrics/foams: supplier-typical weights/rolls (no structural strengths —
 *    used for yardage, mass, and cost planning).
 */
import type { MaterialCategory, MaterialEntry } from "@shared/blueprint";

const IN = 25.4; // mm per inch
const FT = 304.8; // mm per foot

/** Standard dimensional-lumber lengths sold at US yards. */
const LUMBER_LENGTHS = [8, 10, 12, 16].map((ft) => ft * FT);

function lumberSizes(
  sectionWmm: number,
  sectionHmm: number,
  nominal: string,
  costPerLength: Record<number, number>,
): MaterialEntry["stockSizes"] {
  return LUMBER_LENGTHS.map((len, i) => ({
    label: `${nominal} × ${[8, 10, 12, 16][i]} ft`,
    lengthMm: len,
    sectionWidthMm: sectionWmm,
    sectionHeightMm: sectionHmm,
    typicalCostUsd: costPerLength[[8, 10, 12, 16][i]],
  }));
}

export const MATERIALS_CATALOG: MaterialEntry[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // LUMBER — softwood framing (No.2 grade allowable design values)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "lumber.spf_2x4",
    category: "lumber",
    name: "2×4 SPF (Spruce-Pine-Fir) No.2",
    description: "Standard softwood framing stud. Actual section 1.5×3.5 in (38×89 mm).",
    strengthBasis: "allowable",
    densityKgM3: 450,
    elasticModulusMPa: 9650, // 1.4×10⁶ psi
    bendingStrengthMPa: 6.0, // Fb ≈ 875 psi
    shearStrengthMPa: 0.93, // Fv ≈ 135 psi
    stockSizes: lumberSizes(38, 89, "2×4", { 8: 4.5, 10: 6, 12: 8, 16: 12 }),
    typicalCost: { amountUsd: 4.5, per: "each" },
    tags: ["framing", "stud", "carpentry", "softwood"],
    notes: "Allowable design values (No.2, dry service). Not rated for ground contact — use PT for that.",
  },
  {
    key: "lumber.spf_2x6",
    category: "lumber",
    name: "2×6 SPF No.2",
    description: "Softwood framing. Actual 1.5×5.5 in (38×140 mm).",
    strengthBasis: "allowable",
    densityKgM3: 450,
    elasticModulusMPa: 9650,
    bendingStrengthMPa: 6.0,
    shearStrengthMPa: 0.93,
    stockSizes: lumberSizes(38, 140, "2×6", { 8: 7, 10: 9.5, 12: 12, 16: 17 }),
    typicalCost: { amountUsd: 7, per: "each" },
    tags: ["framing", "joist", "rafter", "carpentry"],
  },
  {
    key: "lumber.spf_2x8",
    category: "lumber",
    name: "2×8 SPF No.2",
    description: "Joist/rafter stock. Actual 1.5×7.25 in (38×184 mm).",
    strengthBasis: "allowable",
    densityKgM3: 450,
    elasticModulusMPa: 9650,
    bendingStrengthMPa: 6.0,
    shearStrengthMPa: 0.93,
    stockSizes: lumberSizes(38, 184, "2×8", { 8: 10, 10: 13, 12: 16, 16: 24 }),
    typicalCost: { amountUsd: 10, per: "each" },
    tags: ["framing", "joist", "rafter", "header"],
  },
  {
    key: "lumber.spf_2x10",
    category: "lumber",
    name: "2×10 SPF No.2",
    description: "Joist/beam stock. Actual 1.5×9.25 in (38×235 mm).",
    strengthBasis: "allowable",
    densityKgM3: 450,
    elasticModulusMPa: 9650,
    bendingStrengthMPa: 6.0,
    shearStrengthMPa: 0.93,
    stockSizes: lumberSizes(38, 235, "2×10", { 8: 14, 10: 18, 12: 23, 16: 34 }),
    typicalCost: { amountUsd: 14, per: "each" },
    tags: ["framing", "joist", "beam", "stair-stringer"],
  },
  {
    key: "lumber.spf_2x12",
    category: "lumber",
    name: "2×12 SPF No.2",
    description: "Beam/stringer stock. Actual 1.5×11.25 in (38×286 mm).",
    strengthBasis: "allowable",
    densityKgM3: 450,
    elasticModulusMPa: 9650,
    bendingStrengthMPa: 6.0,
    shearStrengthMPa: 0.93,
    stockSizes: lumberSizes(38, 286, "2×12", { 8: 19, 10: 25, 12: 31, 16: 45 }),
    typicalCost: { amountUsd: 19, per: "each" },
    tags: ["framing", "beam", "stair-stringer", "header"],
  },
  {
    key: "lumber.df_2x4",
    category: "lumber",
    name: "2×4 Douglas Fir-Larch No.2",
    description: "Stronger/heavier West-coast framing alternative to SPF. 38×89 mm actual.",
    strengthBasis: "allowable",
    densityKgM3: 540,
    elasticModulusMPa: 11000, // 1.6×10⁶ psi
    bendingStrengthMPa: 6.2, // Fb ≈ 900 psi
    shearStrengthMPa: 1.24, // Fv ≈ 180 psi
    stockSizes: lumberSizes(38, 89, "2×4 DF", { 8: 6, 10: 8, 12: 10, 16: 15 }),
    typicalCost: { amountUsd: 6, per: "each" },
    tags: ["framing", "stud", "carpentry", "douglas-fir"],
  },
  {
    key: "lumber.syp_2x6",
    category: "lumber",
    name: "2×6 Southern Yellow Pine No.2",
    description: "Dense southern framing pine — common for decks/PT. 38×140 mm actual.",
    strengthBasis: "allowable",
    densityKgM3: 580,
    elasticModulusMPa: 9650, // 1.4×10⁶ psi (SYP #2 2×6)
    bendingStrengthMPa: 6.9, // Fb ≈ 1000 psi
    shearStrengthMPa: 1.21, // Fv ≈ 175 psi
    stockSizes: lumberSizes(38, 140, "2×6 SYP", { 8: 8, 10: 11, 12: 14, 16: 20 }),
    typicalCost: { amountUsd: 8, per: "each" },
    tags: ["framing", "deck", "pressure-treated-base"],
  },
  {
    key: "lumber.pt_4x4",
    category: "lumber",
    name: "4×4 Pressure-Treated (ground contact)",
    description: "PT post, SYP base. Actual 3.5×3.5 in (89×89 mm). Rated for ground contact.",
    strengthBasis: "allowable",
    densityKgM3: 620,
    elasticModulusMPa: 9000,
    bendingStrengthMPa: 5.9,
    shearStrengthMPa: 1.15,
    stockSizes: lumberSizes(89, 89, "4×4 PT", { 8: 13, 10: 17, 12: 21, 16: 32 }),
    typicalCost: { amountUsd: 13, per: "each" },
    tags: ["post", "deck", "fence", "outdoor", "ground-contact"],
    notes: "Use hot-dip galvanized or stainless fasteners — copper-based treatment corrodes plain steel.",
  },
  {
    key: "lumber.pt_6x6",
    category: "lumber",
    name: "6×6 Pressure-Treated post",
    description: "Heavy PT post. Actual 5.5×5.5 in (140×140 mm).",
    strengthBasis: "allowable",
    densityKgM3: 620,
    elasticModulusMPa: 9000,
    bendingStrengthMPa: 5.9,
    shearStrengthMPa: 1.15,
    stockSizes: lumberSizes(140, 140, "6×6 PT", { 8: 30, 10: 40, 12: 50, 16: 75 }),
    typicalCost: { amountUsd: 30, per: "each" },
    tags: ["post", "structure", "pergola", "outdoor"],
  },
  {
    key: "lumber.pine_1x4",
    category: "lumber",
    name: "1×4 Pine board (select)",
    description: "Trim/craft board. Actual 0.75×3.5 in (19×89 mm).",
    strengthBasis: "allowable",
    densityKgM3: 430,
    elasticModulusMPa: 8300,
    bendingStrengthMPa: 5.2,
    shearStrengthMPa: 0.9,
    stockSizes: lumberSizes(19, 89, "1×4", { 8: 7, 10: 9, 12: 11, 16: 15 }),
    typicalCost: { amountUsd: 7, per: "each" },
    tags: ["trim", "craft", "furniture"],
  },
  {
    key: "lumber.oak_red",
    category: "lumber",
    name: "Red Oak (hardwood, S4S)",
    description: "Furniture-grade hardwood, sold by board foot. Strong, heavy, takes stain well.",
    strengthBasis: "ultimate",
    densityKgM3: 700,
    elasticModulusMPa: 12500,
    bendingStrengthMPa: 99, // MOR (ultimate) — calc engine applies wood SF ≈ 2.5+
    shearStrengthMPa: 12.3,
    tensileStrengthMPa: 78,
    stockSizes: [
      { label: "1×6 × 8 ft S4S", lengthMm: 8 * FT, sectionWidthMm: 19, sectionHeightMm: 140, typicalCostUsd: 45 },
      { label: "1×4 × 8 ft S4S", lengthMm: 8 * FT, sectionWidthMm: 19, sectionHeightMm: 89, typicalCostUsd: 30 },
      { label: "4/4 rough board foot", typicalCostUsd: 5 },
    ],
    typicalCost: { amountUsd: 5, per: "each" },
    tags: ["hardwood", "furniture", "cabinetry"],
    notes: "Ultimate (small-clear MOR) values — the calc engine applies a ≥2.5 safety factor for furniture use.",
  },
  {
    key: "lumber.maple_hard",
    category: "lumber",
    name: "Hard Maple (hardwood, S4S)",
    description: "Dense blond hardwood — workbench tops, cutting boards, furniture.",
    strengthBasis: "ultimate",
    densityKgM3: 705,
    elasticModulusMPa: 12600,
    bendingStrengthMPa: 109,
    shearStrengthMPa: 16.1,
    tensileStrengthMPa: 108,
    stockSizes: [
      { label: "1×6 × 8 ft S4S", lengthMm: 8 * FT, sectionWidthMm: 19, sectionHeightMm: 140, typicalCostUsd: 55 },
      { label: "8/4 rough board foot", typicalCostUsd: 9 },
    ],
    typicalCost: { amountUsd: 7, per: "each" },
    tags: ["hardwood", "workbench", "furniture", "food-safe"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SHEET GOODS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "sheet.plywood_cdx_18",
    category: "sheet_good",
    name: "3/4 in CDX Plywood",
    description: "Structural sheathing/shop plywood. 18 mm × 1220×2440 mm (4×8 ft).",
    strengthBasis: "allowable",
    densityKgM3: 550,
    elasticModulusMPa: 8300,
    bendingStrengthMPa: 9.0,
    shearStrengthMPa: 1.3,
    stockSizes: [{ label: "4×8 ft × 3/4 in", widthMm: 1220, lengthMm: 2440, thicknessMm: 18, typicalCostUsd: 55 }],
    typicalCost: { amountUsd: 55, per: "sheet" },
    tags: ["sheathing", "shelf", "shop", "subfloor"],
    notes: "Face-grain direction matters: span ratings assume face grain across supports.",
  },
  {
    key: "sheet.plywood_cdx_12",
    category: "sheet_good",
    name: "1/2 in CDX Plywood",
    description: "12 mm sheathing plywood, 4×8 ft sheet.",
    strengthBasis: "allowable",
    densityKgM3: 550,
    elasticModulusMPa: 8300,
    bendingStrengthMPa: 9.0,
    shearStrengthMPa: 1.3,
    stockSizes: [{ label: "4×8 ft × 1/2 in", widthMm: 1220, lengthMm: 2440, thicknessMm: 12, typicalCostUsd: 42 }],
    typicalCost: { amountUsd: 42, per: "sheet" },
    tags: ["sheathing", "wall", "roof"],
  },
  {
    key: "sheet.plywood_baltic_birch_12",
    category: "sheet_good",
    name: "1/2 in Baltic Birch Plywood",
    description: "Void-free multi-ply birch — jigs, boxes, fine furniture, CNC. 1525×1525 mm sheets.",
    strengthBasis: "allowable",
    densityKgM3: 680,
    elasticModulusMPa: 10000,
    bendingStrengthMPa: 12.0,
    shearStrengthMPa: 1.6,
    stockSizes: [{ label: "5×5 ft × 1/2 in", widthMm: 1525, lengthMm: 1525, thicknessMm: 12, typicalCostUsd: 70 }],
    typicalCost: { amountUsd: 70, per: "sheet" },
    tags: ["furniture", "cnc", "jig", "drawer"],
  },
  {
    key: "sheet.osb_11",
    category: "sheet_good",
    name: "7/16 in OSB",
    description: "Oriented strand board sheathing, 11 mm, 4×8 ft. Cheapest structural panel.",
    strengthBasis: "allowable",
    densityKgM3: 640,
    elasticModulusMPa: 4900,
    bendingStrengthMPa: 6.0,
    shearStrengthMPa: 1.0,
    stockSizes: [{ label: "4×8 ft × 7/16 in", widthMm: 1220, lengthMm: 2440, thicknessMm: 11, typicalCostUsd: 22 }],
    typicalCost: { amountUsd: 22, per: "sheet" },
    tags: ["sheathing", "wall", "roof", "budget"],
    notes: "Swells when wet — not for exposed or wet-service use.",
  },
  {
    key: "sheet.mdf_18",
    category: "sheet_good",
    name: "3/4 in MDF",
    description: "Medium-density fiberboard — flat, paintable, heavy; jigs, templates, paint-grade builds.",
    strengthBasis: "ultimate",
    densityKgM3: 750,
    elasticModulusMPa: 3500,
    bendingStrengthMPa: 22, // MOR
    tensileStrengthMPa: 18,
    stockSizes: [{ label: "4×8 ft × 3/4 in", widthMm: 1220, lengthMm: 2440, thicknessMm: 18, typicalCostUsd: 45 }],
    typicalCost: { amountUsd: 45, per: "sheet" },
    tags: ["template", "paint-grade", "jig", "speaker"],
    notes: "Sags under sustained load and hates moisture — never for shelving spans over ~600 mm unsupported.",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEEL — ASTM minimums, basis: yield
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "steel.sq_tube_1x1_065",
    category: "steel",
    name: "1×1 in square tube × 0.065 in wall (A500)",
    description: "Light welded square tube — frames, carts, brackets. 25.4×25.4×1.65 mm.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 315, // A500 Gr B shaped
    tensileStrengthMPa: 400,
    stockSizes: [
      { label: "1×1×0.065 in × 24 ft", lengthMm: 24 * FT, sectionWidthMm: IN, sectionHeightMm: IN, wallMm: 1.65, typicalCostUsd: 40 },
      { label: "1×1×0.065 in × 4 ft", lengthMm: 4 * FT, sectionWidthMm: IN, sectionHeightMm: IN, wallMm: 1.65, typicalCostUsd: 12 },
    ],
    typicalCost: { amountUsd: 5.5, per: "m" },
    tags: ["tube", "frame", "weld", "cart"],
  },
  {
    key: "steel.sq_tube_1_5x1_5_120",
    category: "steel",
    name: "1.5×1.5 in square tube × 0.120 in wall (A500)",
    description: "Workbench/table frame staple. 38×38×3.05 mm.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 315,
    tensileStrengthMPa: 400,
    stockSizes: [
      { label: "1.5×1.5×0.120 in × 24 ft", lengthMm: 24 * FT, sectionWidthMm: 38.1, sectionHeightMm: 38.1, wallMm: 3.05, typicalCostUsd: 95 },
    ],
    typicalCost: { amountUsd: 13, per: "m" },
    tags: ["tube", "workbench", "frame", "weld"],
  },
  {
    key: "steel.sq_tube_2x2_120",
    category: "steel",
    name: "2×2 in square tube × 0.120 in wall (A500)",
    description: "Heavy frame/trailer tube. 50.8×50.8×3.05 mm.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 315,
    tensileStrengthMPa: 400,
    stockSizes: [
      { label: "2×2×0.120 in × 24 ft", lengthMm: 24 * FT, sectionWidthMm: 50.8, sectionHeightMm: 50.8, wallMm: 3.05, typicalCostUsd: 130 },
    ],
    typicalCost: { amountUsd: 18, per: "m" },
    tags: ["tube", "trailer", "frame", "gate", "structure"],
  },
  {
    key: "steel.sq_tube_2x2_188",
    category: "steel",
    name: "2×2 in square tube × 0.188 in wall (A500)",
    description: "Thick-wall structural tube — axles, high-load frames. 50.8×50.8×4.78 mm.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 315,
    tensileStrengthMPa: 400,
    stockSizes: [
      { label: "2×2×0.188 in × 24 ft", lengthMm: 24 * FT, sectionWidthMm: 50.8, sectionHeightMm: 50.8, wallMm: 4.78, typicalCostUsd: 190 },
    ],
    typicalCost: { amountUsd: 26, per: "m" },
    tags: ["tube", "trailer", "heavy-frame"],
  },
  {
    key: "steel.round_tube_1_od_120",
    category: "steel",
    name: "1 in OD round tube × 0.120 wall (DOM)",
    description: "DOM (drawn-over-mandrel) round tube — roll bars, handles, linkages. 25.4 mm OD × 3.05 wall.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 350,
    tensileStrengthMPa: 480,
    stockSizes: [
      { label: '1" OD ×0.120 DOM × 6 ft', lengthMm: 6 * FT, sectionWidthMm: 25.4, sectionHeightMm: 25.4, wallMm: 3.05, typicalCostUsd: 45 },
    ],
    typicalCost: { amountUsd: 25, per: "m" },
    tags: ["tube", "round", "rollcage", "handle"],
  },
  {
    key: "steel.chromoly_4130_tube",
    category: "steel",
    name: '4130 Chromoly tube 1.25" OD × 0.065 wall (normalized)',
    description: "Aircraft/race-spec alloy tube — high strength-to-weight for vehicle frames and cages.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 205000,
    yieldStrengthMPa: 435,
    tensileStrengthMPa: 670,
    stockSizes: [
      { label: '1.25" OD × 0.065 × 6 ft', lengthMm: 6 * FT, sectionWidthMm: 31.75, sectionHeightMm: 31.75, wallMm: 1.65, typicalCostUsd: 60 },
    ],
    typicalCost: { amountUsd: 33, per: "m" },
    tags: ["chromoly", "vehicle", "cage", "aircraft", "tig"],
    notes: "TIG-weld; normalize/stress-relieve considerations apply for critical joints.",
  },
  {
    key: "steel.angle_1_5x1_5_125",
    category: "steel",
    name: "1.5×1.5 in angle × 1/8 in (A36)",
    description: "Hot-rolled angle iron — brackets, frames, edging. 38×38×3.2 mm.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 250,
    tensileStrengthMPa: 400,
    stockSizes: [
      { label: "1.5×1.5×1/8 angle × 20 ft", lengthMm: 20 * FT, sectionWidthMm: 38.1, sectionHeightMm: 38.1, wallMm: 3.18, typicalCostUsd: 55 },
    ],
    typicalCost: { amountUsd: 9, per: "m" },
    tags: ["angle", "bracket", "frame", "a36"],
  },
  {
    key: "steel.flat_bar_2x0_25",
    category: "steel",
    name: "2 in × 1/4 in flat bar (A36)",
    description: "Hot-rolled flat — gussets, tabs, brackets. 50.8×6.35 mm.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 250,
    tensileStrengthMPa: 400,
    stockSizes: [
      { label: "2×1/4 flat × 20 ft", lengthMm: 20 * FT, sectionWidthMm: 50.8, sectionHeightMm: 6.35, typicalCostUsd: 60 },
    ],
    typicalCost: { amountUsd: 10, per: "m" },
    tags: ["flat-bar", "gusset", "bracket"],
  },
  {
    key: "steel.sheet_16ga",
    category: "steel",
    name: "16 ga (1.5 mm) mild steel sheet",
    description: "Cold-rolled sheet — enclosures, panels, brackets.",
    strengthBasis: "yield",
    densityKgM3: 7850,
    elasticModulusMPa: 200000,
    yieldStrengthMPa: 240,
    tensileStrengthMPa: 370,
    stockSizes: [
      { label: "4×8 ft × 16 ga", widthMm: 1220, lengthMm: 2440, thicknessMm: 1.52, typicalCostUsd: 120 },
      { label: "2×4 ft × 16 ga", widthMm: 610, lengthMm: 1220, thicknessMm: 1.52, typicalCostUsd: 40 },
    ],
    typicalCost: { amountUsd: 40, per: "m2" },
    tags: ["sheet", "panel", "enclosure", "bend"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ALUMINUM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "alu.6061_sq_tube_1x1_125",
    category: "aluminum",
    name: "6061-T6 square tube 1×1 in × 1/8 wall",
    description: "Light, weldable structural aluminum tube. 25.4×25.4×3.2 mm.",
    strengthBasis: "yield",
    densityKgM3: 2700,
    elasticModulusMPa: 68900,
    yieldStrengthMPa: 276,
    tensileStrengthMPa: 310,
    stockSizes: [
      { label: "1×1×1/8 × 8 ft", lengthMm: 8 * FT, sectionWidthMm: 25.4, sectionHeightMm: 25.4, wallMm: 3.18, typicalCostUsd: 35 },
    ],
    typicalCost: { amountUsd: 14, per: "m" },
    tags: ["aluminum", "tube", "lightweight", "frame"],
    notes: "Welding anneals the HAZ to ~T4 (yield drops to ≈115 MPa) — bolt or rivet critical joints, or derate.",
  },
  {
    key: "alu.6061_angle_1_5",
    category: "aluminum",
    name: "6061-T6 angle 1.5×1.5 in × 1/8",
    description: "Aluminum angle — light brackets and rails. 38×38×3.2 mm.",
    strengthBasis: "yield",
    densityKgM3: 2700,
    elasticModulusMPa: 68900,
    yieldStrengthMPa: 276,
    tensileStrengthMPa: 310,
    stockSizes: [
      { label: "1.5×1.5×1/8 × 8 ft", lengthMm: 8 * FT, sectionWidthMm: 38.1, sectionHeightMm: 38.1, wallMm: 3.18, typicalCostUsd: 30 },
    ],
    typicalCost: { amountUsd: 12, per: "m" },
    tags: ["aluminum", "angle", "bracket"],
  },
  {
    key: "alu.tslot_2020",
    category: "aluminum",
    name: "2020 T-slot extrusion (6063-T5)",
    description: "20×20 mm modular T-slot — printer frames, jigs, light automation.",
    strengthBasis: "yield",
    densityKgM3: 2700,
    elasticModulusMPa: 68900,
    yieldStrengthMPa: 145, // 6063-T5
    tensileStrengthMPa: 186,
    stockSizes: [
      { label: "2020 × 1 m", lengthMm: 1000, sectionWidthMm: 20, sectionHeightMm: 20, typicalCostUsd: 8 },
      { label: "2020 × 2 m", lengthMm: 2000, sectionWidthMm: 20, sectionHeightMm: 20, typicalCostUsd: 15 },
    ],
    typicalCost: { amountUsd: 8, per: "m" },
    tags: ["t-slot", "extrusion", "printer", "jig", "modular"],
  },
  {
    key: "alu.tslot_4040",
    category: "aluminum",
    name: "4040 T-slot extrusion (6063-T5)",
    description: "40×40 mm T-slot — machine bases, benches, CNC gantries.",
    strengthBasis: "yield",
    densityKgM3: 2700,
    elasticModulusMPa: 68900,
    yieldStrengthMPa: 145,
    tensileStrengthMPa: 186,
    stockSizes: [
      { label: "4040 × 1 m", lengthMm: 1000, sectionWidthMm: 40, sectionHeightMm: 40, typicalCostUsd: 20 },
      { label: "4040 × 2 m", lengthMm: 2000, sectionWidthMm: 40, sectionHeightMm: 40, typicalCostUsd: 38 },
    ],
    typicalCost: { amountUsd: 20, per: "m" },
    tags: ["t-slot", "extrusion", "cnc", "machine-frame"],
  },
  {
    key: "alu.sheet_5052_125",
    category: "aluminum",
    name: "5052-H32 aluminum sheet 1/8 in",
    description: "Formable marine-grade sheet — panels, boxes, brackets. 3.2 mm.",
    strengthBasis: "yield",
    densityKgM3: 2680,
    elasticModulusMPa: 70300,
    yieldStrengthMPa: 193,
    tensileStrengthMPa: 228,
    stockSizes: [
      { label: "2×4 ft × 1/8 in", widthMm: 610, lengthMm: 1220, thicknessMm: 3.18, typicalCostUsd: 70 },
    ],
    typicalCost: { amountUsd: 95, per: "m2" },
    tags: ["aluminum", "sheet", "panel", "marine", "bend"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FASTENERS — capacities are indicative single-fastener values
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "fastener.wood_screw_8",
    category: "fastener",
    name: "#8 wood screw (1¼–3 in)",
    description: "General wood screw. Indicative lateral (shear) capacity ≈ 400 N in SPF; withdrawal ≈ 500 N per inch of thread.",
    strengthBasis: "allowable",
    stockSizes: [
      { label: '#8 × 1¼" (100 ct)', lengthMm: 32, typicalCostUsd: 8 },
      { label: '#8 × 2½" (100 ct)', lengthMm: 64, typicalCostUsd: 10 },
    ],
    typicalCost: { amountUsd: 0.1, per: "each" },
    tags: ["screw", "wood", "carpentry"],
  },
  {
    key: "fastener.structural_screw_gsr",
    category: "fastener",
    name: 'Structural screw ¼" (GRK/Spax type)',
    description: "Engineered structural screw — ledger/joinery rated. Indicative shear ≈ 1.6 kN in SPF pairs.",
    strengthBasis: "allowable",
    stockSizes: [
      { label: '¼" × 3⅛" (50 ct)', lengthMm: 79, typicalCostUsd: 25 },
      { label: '¼" × 4" (50 ct)', lengthMm: 102, typicalCostUsd: 30 },
    ],
    typicalCost: { amountUsd: 0.55, per: "each" },
    tags: ["structural", "ledger", "screw"],
    notes: "Use the manufacturer's ESR load tables for real connection design.",
  },
  {
    key: "fastener.lag_3_8",
    category: "fastener",
    name: '3/8" lag bolt',
    description: "Heavy wood lag. Indicative shear ≈ 2.2 kN in SPF main member.",
    strengthBasis: "allowable",
    stockSizes: [{ label: '3/8" × 4" (each)', lengthMm: 102, typicalCostUsd: 1.2 }],
    typicalCost: { amountUsd: 1.2, per: "each" },
    tags: ["lag", "bolt", "wood", "heavy"],
  },
  {
    key: "fastener.hex_m8_88",
    category: "fastener",
    name: "M8 hex bolt, grade 8.8",
    description: "Metric machine bolt. Proof ≈ 21.2 kN; single-shear capacity ≈ 11 kN (threads excluded).",
    strengthBasis: "yield",
    yieldStrengthMPa: 640,
    tensileStrengthMPa: 800,
    stockSizes: [{ label: "M8 × 40 (25 ct)", lengthMm: 40, typicalCostUsd: 9 }],
    typicalCost: { amountUsd: 0.36, per: "each" },
    tags: ["bolt", "metric", "machine"],
  },
  {
    key: "fastener.hex_m10_88",
    category: "fastener",
    name: "M10 hex bolt, grade 8.8",
    description: "Metric machine bolt. Proof ≈ 33.7 kN; single-shear ≈ 17 kN.",
    strengthBasis: "yield",
    yieldStrengthMPa: 640,
    tensileStrengthMPa: 800,
    stockSizes: [{ label: "M10 × 50 (20 ct)", lengthMm: 50, typicalCostUsd: 12 }],
    typicalCost: { amountUsd: 0.6, per: "each" },
    tags: ["bolt", "metric", "machine"],
  },
  {
    key: "fastener.carriage_1_2",
    category: "fastener",
    name: '1/2" carriage bolt (grade 2)',
    description: "Timber connection bolt. Single-shear ≈ 12 kN steel-limited; wood bearing usually governs.",
    strengthBasis: "yield",
    yieldStrengthMPa: 393,
    tensileStrengthMPa: 510,
    stockSizes: [{ label: '1/2" × 6" (each)', lengthMm: 152, typicalCostUsd: 2.2 }],
    typicalCost: { amountUsd: 2.2, per: "each" },
    tags: ["carriage", "timber", "bolt"],
  },
  {
    key: "fastener.pocket_screw",
    category: "fastener",
    name: "Pocket-hole screw (Kreg type)",
    description: "Self-tapping washer-head screw for pocket joinery in furniture.",
    strengthBasis: "allowable",
    stockSizes: [
      { label: '1¼" coarse (100 ct)', lengthMm: 32, typicalCostUsd: 9 },
      { label: '2½" coarse (50 ct)', lengthMm: 64, typicalCostUsd: 9 },
    ],
    typicalCost: { amountUsd: 0.12, per: "each" },
    tags: ["pocket-hole", "furniture", "joinery"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3D-PRINT FILAMENTS — datasheet typicals; Z-strength = tensile × layerAdhesionFactor
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "filament.pla",
    category: "filament",
    name: "PLA filament",
    description: "Default rigid filament — stiff, precise, easy. Brittle under impact, softens ~55–60 °C.",
    strengthBasis: "ultimate",
    densityKgM3: 1240,
    elasticModulusMPa: 3500,
    tensileStrengthMPa: 60,
    layerAdhesionFactor: 0.65,
    maxServiceTempC: 55,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 20 }],
    typicalCost: { amountUsd: 20, per: "spool" },
    tags: ["pla", "rigid", "prototyping", "easy"],
    notes: "Never for parts in hot cars or sun-load — creeps and warps above ~55 °C.",
  },
  {
    key: "filament.petg",
    category: "filament",
    name: "PETG filament",
    description: "Tough all-rounder — outdoor-tolerant, slightly flexible, ~80 °C service.",
    strengthBasis: "ultimate",
    densityKgM3: 1270,
    elasticModulusMPa: 2100,
    tensileStrengthMPa: 50,
    layerAdhesionFactor: 0.75,
    maxServiceTempC: 75,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 22 }],
    typicalCost: { amountUsd: 22, per: "spool" },
    tags: ["petg", "functional", "outdoor"],
  },
  {
    key: "filament.abs",
    category: "filament",
    name: "ABS filament",
    description: "Classic engineering plastic — ~95 °C service, machinable, acetone-smoothable. Needs enclosure.",
    strengthBasis: "ultimate",
    densityKgM3: 1040,
    elasticModulusMPa: 2200,
    tensileStrengthMPa: 40,
    layerAdhesionFactor: 0.6,
    maxServiceTempC: 95,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 22 }],
    typicalCost: { amountUsd: 22, per: "spool" },
    tags: ["abs", "engineering", "heat", "enclosure-required"],
  },
  {
    key: "filament.asa",
    category: "filament",
    name: "ASA filament",
    description: "UV-stable ABS alternative — the pick for long-term outdoor parts.",
    strengthBasis: "ultimate",
    densityKgM3: 1070,
    elasticModulusMPa: 2300,
    tensileStrengthMPa: 45,
    layerAdhesionFactor: 0.6,
    maxServiceTempC: 95,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 28 }],
    typicalCost: { amountUsd: 28, per: "spool" },
    tags: ["asa", "uv-stable", "outdoor"],
  },
  {
    key: "filament.tpu95",
    category: "filament",
    name: "TPU 95A filament",
    description: "Flexible rubber-like — gaskets, bumpers, grips, costume flexibility.",
    strengthBasis: "ultimate",
    densityKgM3: 1210,
    elasticModulusMPa: 26, // ~95A durometer flexural behavior
    tensileStrengthMPa: 30,
    layerAdhesionFactor: 0.85,
    maxServiceTempC: 80,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 30 }],
    typicalCost: { amountUsd: 30, per: "spool" },
    tags: ["tpu", "flexible", "gasket", "costume"],
  },
  {
    key: "filament.nylon_pa12",
    category: "filament",
    name: "Nylon PA12 filament",
    description: "Tough, fatigue-resistant, low-friction — gears, hinges, functional mechanisms.",
    strengthBasis: "ultimate",
    densityKgM3: 1010,
    elasticModulusMPa: 1700,
    tensileStrengthMPa: 50,
    layerAdhesionFactor: 0.7,
    maxServiceTempC: 110,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 45 }],
    typicalCost: { amountUsd: 45, per: "spool" },
    tags: ["nylon", "gear", "wear", "dry-before-printing"],
    notes: "Hygroscopic — must be dried and printed from a drybox.",
  },
  {
    key: "filament.pla_cf",
    category: "filament",
    name: "PLA-CF (carbon-fiber PLA)",
    description: "Chopped-CF-filled PLA — very stiff, matte, dimensionally stable jigs/brackets.",
    strengthBasis: "ultimate",
    densityKgM3: 1290,
    elasticModulusMPa: 5500,
    tensileStrengthMPa: 55,
    layerAdhesionFactor: 0.55,
    maxServiceTempC: 55,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 35 }],
    typicalCost: { amountUsd: 35, per: "spool" },
    tags: ["carbon", "stiff", "jig", "hardened-nozzle"],
    notes: "Requires a hardened nozzle; stiffer but NOT stronger in Z than plain PLA.",
  },
  {
    key: "filament.pc",
    category: "filament",
    name: "Polycarbonate (PC) filament",
    description: "Highest-strength common FDM material — ~110 °C service. Demands a hot, enclosed printer.",
    strengthBasis: "ultimate",
    densityKgM3: 1200,
    elasticModulusMPa: 2300,
    tensileStrengthMPa: 65,
    layerAdhesionFactor: 0.6,
    maxServiceTempC: 110,
    stockSizes: [{ label: "1 kg spool (1.75 mm)", massG: 1000, typicalCostUsd: 40 }],
    typicalCost: { amountUsd: 40, per: "spool" },
    tags: ["pc", "strong", "heat", "enclosure-required"],
  },
  {
    key: "resin.standard",
    category: "resin",
    name: "Standard SLA resin",
    description: "High-detail resin for miniatures/masters — rigid but brittle; UV-degrades outdoors.",
    strengthBasis: "ultimate",
    densityKgM3: 1150,
    elasticModulusMPa: 2200,
    tensileStrengthMPa: 50,
    maxServiceTempC: 60,
    stockSizes: [{ label: "1 kg bottle", massG: 1000, typicalCostUsd: 25 }],
    typicalCost: { amountUsd: 25, per: "kg" },
    tags: ["resin", "sla", "detail", "miniature", "brittle"],
  },
  {
    key: "resin.tough",
    category: "resin",
    name: "Tough (ABS-like) SLA resin",
    description: "Impact-modified resin for functional resin prints, snap fits.",
    strengthBasis: "ultimate",
    densityKgM3: 1120,
    elasticModulusMPa: 1900,
    tensileStrengthMPa: 45,
    maxServiceTempC: 70,
    stockSizes: [{ label: "1 kg bottle", massG: 1000, typicalCostUsd: 35 }],
    typicalCost: { amountUsd: 35, per: "kg" },
    tags: ["resin", "tough", "functional"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // FABRICS & COSTUME MATERIALS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "fabric.muslin",
    category: "fabric",
    name: "Muslin (unbleached cotton)",
    description: "Cheap mockup/toile fabric — always pattern-test in muslin before cutting good fabric.",
    strengthBasis: "ultimate",
    arealDensityGM2: 120,
    stretch: "none",
    stockSizes: [{ label: '45" wide, by the yard', widthMm: 1143, typicalCostUsd: 4 }],
    typicalCost: { amountUsd: 4, per: "yd" },
    tags: ["mockup", "toile", "cotton", "lining"],
  },
  {
    key: "fabric.cotton_broadcloth",
    category: "fabric",
    name: "Cotton broadcloth",
    description: "Light woven cotton — shirts, linings, general costume body fabric.",
    strengthBasis: "ultimate",
    arealDensityGM2: 130,
    stretch: "none",
    stockSizes: [{ label: '45" wide, by the yard', widthMm: 1143, typicalCostUsd: 6 }],
    typicalCost: { amountUsd: 6, per: "yd" },
    tags: ["cotton", "shirt", "costume", "woven"],
  },
  {
    key: "fabric.canvas_10oz",
    category: "fabric",
    name: "10 oz cotton duck canvas",
    description: "Heavy woven canvas — bags, aprons, structured costume pieces, tool rolls.",
    strengthBasis: "ultimate",
    arealDensityGM2: 340,
    stretch: "none",
    stockSizes: [{ label: '60" wide, by the yard', widthMm: 1524, typicalCostUsd: 9 }],
    typicalCost: { amountUsd: 9, per: "yd" },
    tags: ["canvas", "heavy", "bag", "workwear"],
  },
  {
    key: "fabric.spandex_4way",
    category: "fabric",
    name: "4-way stretch spandex (nylon/lycra)",
    description: "Bodysuit/undersuit fabric — cut smaller than body measurements (negative ease).",
    strengthBasis: "ultimate",
    arealDensityGM2: 200,
    stretch: "4-way",
    stockSizes: [{ label: '58–60" wide, by the yard', widthMm: 1500, typicalCostUsd: 10 }],
    typicalCost: { amountUsd: 10, per: "yd" },
    tags: ["spandex", "bodysuit", "stretch", "cosplay"],
    notes: "Use a stretch needle + zigzag/serger seams; pattern with 10–25% negative ease.",
  },
  {
    key: "fabric.twill_bull_denim",
    category: "fabric",
    name: "Bull denim / heavy twill",
    description: "Structured non-stretch bottom-weight — jackets, pants, armor-backing.",
    strengthBasis: "ultimate",
    arealDensityGM2: 400,
    stretch: "none",
    stockSizes: [{ label: '60" wide, by the yard', widthMm: 1524, typicalCostUsd: 11 }],
    typicalCost: { amountUsd: 11, per: "yd" },
    tags: ["twill", "denim", "jacket", "structure"],
  },
  {
    key: "fabric.faux_leather",
    category: "fabric",
    name: "Faux leather (PU)",
    description: "Costume leather look — belts, straps, armor wraps. Doesn't fray; topstitch, don't iron.",
    strengthBasis: "ultimate",
    arealDensityGM2: 550,
    stretch: "2-way",
    stockSizes: [{ label: '54" wide, by the yard', widthMm: 1372, typicalCostUsd: 15 }],
    typicalCost: { amountUsd: 15, per: "yd" },
    tags: ["leather-look", "strap", "armor", "cosplay"],
  },
  {
    key: "fabric.felt_craft",
    category: "fabric",
    name: "Craft felt (acrylic)",
    description: "Non-fray craft sheet — appliqué, padding, prop details.",
    strengthBasis: "ultimate",
    arealDensityGM2: 250,
    stretch: "none",
    stockSizes: [{ label: '72" wide, by the yard', widthMm: 1829, typicalCostUsd: 7 }],
    typicalCost: { amountUsd: 7, per: "yd" },
    tags: ["felt", "craft", "applique"],
  },
  {
    key: "foam.eva_10mm",
    category: "foam",
    name: "EVA foam 10 mm (high density)",
    description: "The cosplay-armor staple — heat-formable, carvable, contact-cement joins.",
    strengthBasis: "ultimate",
    densityKgM3: 85,
    stockSizes: [
      { label: "1 m × 2 m × 10 mm sheet", widthMm: 1000, lengthMm: 2000, thicknessMm: 10, typicalCostUsd: 25 },
    ],
    typicalCost: { amountUsd: 25, per: "sheet" },
    tags: ["eva", "cosplay", "armor", "heat-form"],
    notes: "Seal with plastidip/flexbond before painting. Heat-shape at ~120–150 °C with a heat gun.",
  },
  {
    key: "foam.eva_4mm",
    category: "foam",
    name: "EVA foam 4 mm",
    description: "Detail-layer EVA for trim, bevels, and thin overlays.",
    strengthBasis: "ultimate",
    densityKgM3: 85,
    stockSizes: [
      { label: "1 m × 2 m × 4 mm sheet", widthMm: 1000, lengthMm: 2000, thicknessMm: 4, typicalCostUsd: 15 },
    ],
    typicalCost: { amountUsd: 15, per: "sheet" },
    tags: ["eva", "detail", "trim", "cosplay"],
  },
  {
    key: "thermo.worbla_classic",
    category: "thermoplastic",
    name: "Worbla Finest Art (thermoplastic sheet)",
    description: "Heat-activated (~90 °C) moldable sheet — sandwiches EVA for rigid armor shells; scraps re-blend.",
    strengthBasis: "ultimate",
    densityKgM3: 1100,
    maxServiceTempC: 80,
    stockSizes: [
      { label: "Medium sheet 750×500 mm", widthMm: 500, lengthMm: 750, thicknessMm: 1, typicalCostUsd: 45 },
      { label: "Jumbo sheet 1000×1500 mm", widthMm: 1000, lengthMm: 1500, thicknessMm: 1, typicalCostUsd: 110 },
    ],
    typicalCost: { amountUsd: 45, per: "sheet" },
    tags: ["worbla", "thermoplastic", "armor", "cosplay"],
  },
  {
    key: "notion.zipper_sep",
    category: "notion",
    name: "Separating zipper (jacket)",
    description: "#5 molded separating zipper for closures.",
    strengthBasis: "ultimate",
    stockSizes: [
      { label: '22" separating', lengthMm: 559, typicalCostUsd: 5 },
      { label: '30" separating', lengthMm: 762, typicalCostUsd: 6.5 },
    ],
    typicalCost: { amountUsd: 5, per: "each" },
    tags: ["zipper", "closure", "notion"],
  },
  {
    key: "notion.velcro_2in",
    category: "notion",
    name: '2" sew-on hook & loop (Velcro)',
    description: "Adjustable closure strap material for costumes and gear.",
    strengthBasis: "ultimate",
    stockSizes: [{ label: '2" × 1 yd', lengthMm: 914, widthMm: 50.8, typicalCostUsd: 4 }],
    typicalCost: { amountUsd: 4, per: "yd" },
    tags: ["velcro", "closure", "strap"],
  },
  {
    key: "notion.webbing_1in",
    category: "notion",
    name: '1" nylon webbing',
    description: "Strap/harness webbing — ~2.7 kN typical break strength.",
    strengthBasis: "ultimate",
    tensileStrengthMPa: 0, // strength is per-strap: see notes
    stockSizes: [{ label: '1" × 10 yd roll', lengthMm: 9144, widthMm: 25.4, typicalCostUsd: 9 }],
    typicalCost: { amountUsd: 1, per: "yd" },
    tags: ["webbing", "strap", "harness"],
    notes: "Typical flat-webbing break ≈ 600 lbf (2.7 kN) per strap — never for life-safety use.",
  },
];

// ---------------------------------------------------------------------------
// Lookup / search API (used by the router and the agent tool)
// ---------------------------------------------------------------------------

const byKey = new Map(MATERIALS_CATALOG.map((m) => [m.key, m]));

export function getMaterial(key: string): MaterialEntry | undefined {
  return byKey.get(key);
}

export function listCategories(): MaterialCategory[] {
  return [...new Set(MATERIALS_CATALOG.map((m) => m.category))];
}

/** Simple ranked text search over name/description/tags/key. */
export function searchMaterials(query: string, category?: MaterialCategory, limit = 20): MaterialEntry[] {
  const q = query.trim().toLowerCase();
  const pool = category ? MATERIALS_CATALOG.filter((m) => m.category === category) : MATERIALS_CATALOG;
  if (!q) return pool.slice(0, limit);
  const terms = q.split(/\s+/).filter(Boolean);
  const scored = pool
    .map((m) => {
      const hay = `${m.key} ${m.name} ${m.description} ${m.tags.join(" ")}`.toLowerCase();
      let score = 0;
      for (const t of terms) {
        if (m.name.toLowerCase().includes(t)) score += 3;
        else if (m.tags.some((tag) => tag.includes(t))) score += 2;
        else if (hay.includes(t)) score += 1;
      }
      return { m, score };
    })
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score);
  return scored.slice(0, limit).map((s) => s.m);
}
