/**
 * Unified data layer — libSQL / SQLite (single engine for all modes).
 *
 * - Local Sovereign mode (default): an embedded file database (`file:<path>`),
 *   zero-infra and air-gappable.
 * - Networked / multi-node: set `LIBSQL_URL` (or `TURSO_DATABASE_URL`) to a
 *   libsql/Turso endpoint (+ `LIBSQL_AUTH_TOKEN`) for a shared/replicated DB.
 *
 * `getDb()` always returns a live drizzle instance (it is never null) — every
 * router works in every mode. Schema lives in `drizzle/schema.ts`; migrations
 * generated by drizzle-kit are applied automatically on first connect.
 */
import { createClient, type Client } from "@libsql/client";
import { drizzle, type LibSQLDatabase } from "drizzle-orm/libsql";
import { migrate } from "drizzle-orm/libsql/migrator";
import { eq, asc, desc, lt, sql } from "drizzle-orm";
import path from "path";
import fs from "fs";
import * as schema from "../drizzle/schema.js";
import {
  InsertUser,
  users,
  type User,
  chatSessions,
  chatMessages,
  auditLog,
  InsertChatSession,
  InsertChatMessage,
  InsertAuditLog,
} from "../drizzle/schema.js";
import { ENV } from "./_core/env.js";
import { PATHS } from "./_core/paths.js";
import { createLogger } from "./_core/logger.js";

const log = createLogger("db");

export type Db = LibSQLDatabase<typeof schema>;

let _client: Client | null = null;
let _db: Db | null = null;
let _initPromise: Promise<Db> | null = null;
let _migrationFailed = false;

/** Returns whether the auto-migration on first connect succeeded. */
export function getMigrationStatus(): { ok: boolean } {
  return { ok: !_migrationFailed };
}

// MIGRATIONS_DIR is set by the Electron main process as an env var so the
// absolute path is known before the backend bundle executes. Falls back to
// process.cwd()-relative path for dev mode and non-Electron deployments.
const MIGRATIONS_DIR = process.env.MIGRATIONS_DIR ?? path.join(process.cwd(), "drizzle", "migrations");

/** Resolve the libSQL connection URL (remote when configured, else local file). */
function resolveUrl(): { url: string; authToken?: string } {
  const remote = process.env.LIBSQL_URL || process.env.TURSO_DATABASE_URL;
  if (remote) {
    return { url: remote, authToken: process.env.LIBSQL_AUTH_TOKEN || process.env.TURSO_AUTH_TOKEN };
  }
  const filePath = process.env.SQLITE_PATH ?? PATHS.sqlite;
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return { url: `file:${filePath}` };
}

async function init(): Promise<Db> {
  const { url, authToken } = resolveUrl();
  _client = createClient({ url, authToken });
  const db = drizzle(_client, { schema });

  // Local file DBs benefit from WAL; ignore for remote where it's not applicable.
  if (url.startsWith("file:")) {
    try {
      await _client.execute("PRAGMA journal_mode = WAL");
      await _client.execute("PRAGMA foreign_keys = ON");
    } catch (err) {
      log.warn("Failed to set SQLite pragmas", err);
    }
  }

  // Runtime fallback: apply generated migrations on first connect so the schema
  // exists out-of-the-box. Non-fatal — a failure logs a warning but does not abort
  // boot. This is one of three paths onto the same `drizzle/migrations/`: `pnpm
  // build:push` (dev: regenerate from schema + apply) and `pnpm db:migrate` (prod/CI:
  // apply explicitly before `pnpm start`, the fail-loud alternative to this fallback).
  try {
    if (fs.existsSync(MIGRATIONS_DIR)) {
      await migrate(db, { migrationsFolder: MIGRATIONS_DIR });
    } else {
      log.warn(`No migrations folder at ${MIGRATIONS_DIR} — run \`pnpm build:push\``);
    }
  } catch (err) {
    _migrationFailed = true;
    log.warn("Auto-migration failed — server continuing with existing schema. Run `pnpm db:migrate` to apply pending migrations.", err);
  }

  _db = db;
  log.info("Database ready", { url: url.startsWith("file:") ? url : "<remote libsql>" });
  return db;
}

/** Get the live drizzle instance (initializes + migrates on first call). */
export async function getDb(): Promise<Db> {
  if (_db) return _db;
  if (!_initPromise) _initPromise = init();
  return _initPromise;
}

/**
 * Get the underlying libSQL client, sharing the SAME connection as `getDb()`
 * (critical for in-memory test DBs, where a second connection sees no data).
 * Ensures the DB is initialized first. Use this only for features that need raw
 * SQL beyond Drizzle's builder — e.g. libSQL-native vector search
 * (`vector_top_k` / `libsql_vector_idx`), which Drizzle has no helper for.
 */
export async function getLibsqlClient(): Promise<Client> {
  await getDb();
  if (!_client) throw new Error("libSQL client not initialized");
  return _client;
}

// ─────────────────────────────────────────────────────────────────────────────
// Users
// ─────────────────────────────────────────────────────────────────────────────

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb();
  const now = new Date();

  const existing = await db.select().from(users).where(eq(users.openId, user.openId)).limit(1);

  if (existing.length > 0) {
    const update: Partial<InsertUser> = { updatedAt: now, lastSignedIn: now };
    if (user.name !== undefined) update.name = user.name;
    if (user.email !== undefined) update.email = user.email;
    if (user.loginMethod !== undefined) update.loginMethod = user.loginMethod;
    if (user.passwordHash !== undefined) update.passwordHash = user.passwordHash;
    if (user.role !== undefined) update.role = user.role;
    if (user.executionMode !== undefined) update.executionMode = user.executionMode;
    if (user.lastSignedIn !== undefined) update.lastSignedIn = user.lastSignedIn;
    await db.update(users).set(update).where(eq(users.openId, user.openId));
  } else {
    const role = user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : undefined);
    await db.insert(users).values({
      ...user,
      ...(role ? { role } : {}),
      createdAt: user.createdAt ?? now,
      updatedAt: now,
      lastSignedIn: user.lastSignedIn ?? now,
    });
  }
}

export async function getUserByOpenId(openId: string) {
  const db = await getDb();
  const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1);
  return result.length > 0 ? result[0] : undefined;
}

/**
 * Project a user row down to the fields that are safe to send to a client over
 * the network. The full `users` row carries `passwordHash` (and other internal
 * columns), so callers that return a user in an API response — e.g. the mobile
 * pairing redeem — MUST sanitize through this rather than shipping the raw row.
 */
export function publicUser(user: User | undefined | null) {
  if (!user) return null;
  return {
    id: user.id,
    openId: user.openId,
    name: user.name,
    role: user.role,
    executionMode: user.executionMode,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Chat Persistence
// ─────────────────────────────────────────────────────────────────────────────

export async function createChatSession(session: InsertChatSession) {
  const db = await getDb();
  await db.insert(chatSessions).values(session);
}

export async function getChatSessions(projectId: string) {
  const db = await getDb();
  return db
    .select()
    .from(chatSessions)
    .where(eq(chatSessions.projectId, projectId))
    .orderBy(desc(chatSessions.createdAt));
}

export async function getChatSession(sessionId: string) {
  const db = await getDb();
  const result = await db.select().from(chatSessions).where(eq(chatSessions.id, sessionId)).limit(1);
  return result.length > 0 ? result[0] : undefined;
}

export async function updateChatSession(sessionId: string, updates: Partial<InsertChatSession>) {
  const db = await getDb();
  await db
    .update(chatSessions)
    .set({ ...updates, updatedAt: new Date() })
    .where(eq(chatSessions.id, sessionId));
}

export async function addChatMessage(message: InsertChatMessage) {
  const db = await getDb();
  await db.insert(chatMessages).values(message);
}

export async function getChatMessages(sessionId: string) {
  const db = await getDb();
  return db
    .select()
    .from(chatMessages)
    .where(eq(chatMessages.sessionId, sessionId))
    .orderBy(asc(chatMessages.createdAt));
}

// ─────────────────────────────────────────────────────────────────────────────
// Audit log — append-only; retention purge is the only deletion path
// ─────────────────────────────────────────────────────────────────────────────

export async function auditInsert(entry: InsertAuditLog): Promise<void> {
  const db = await getDb();
  await db.insert(auditLog).values(entry);
}

/** Delete entries older than `cutoff`; returns the number of rows removed. */
export async function auditPurgeBefore(cutoff: Date): Promise<number> {
  const db = await getDb();
  const result = await db.delete(auditLog).where(lt(auditLog.createdAt, cutoff));
  return Number((result as unknown as { rowsAffected?: number }).rowsAffected ?? 0);
}

export async function auditList(limit: number, offset: number) {
  const db = await getDb();
  const [entries, countRows] = await Promise.all([
    db.select().from(auditLog).orderBy(desc(auditLog.createdAt)).limit(limit).offset(offset),
    db.select({ count: sql<number>`count(*)` }).from(auditLog),
  ]);
  return { entries, total: Number(countRows[0]?.count ?? 0) };
}

export async function auditListByActor(actorId: number, limit: number) {
  const db = await getDb();
  return db
    .select()
    .from(auditLog)
    .where(eq(auditLog.actorId, actorId))
    .orderBy(desc(auditLog.createdAt))
    .limit(limit);
}

export async function auditStats(): Promise<{
  dbActive: boolean;
  entries: number;
  oldestEntryAt: string | null;
  approxBytes: number;
}> {
  const db = await getDb();
  const [countRows, oldestRows] = await Promise.all([
    db.select({ count: sql<number>`count(*)` }).from(auditLog),
    db.select({ oldest: sql<number | null>`min(${auditLog.createdAt})` }).from(auditLog),
  ]);
  const entries = Number(countRows[0]?.count ?? 0);
  const oldestRaw = oldestRows[0]?.oldest ?? null;
  // createdAt is stored as a unix-seconds integer (timestamp mode).
  const oldestEntryAt = oldestRaw ? new Date(Number(oldestRaw) * 1000).toISOString() : null;
  return { dbActive: true, entries, oldestEntryAt, approxBytes: entries * 768 };
}
